packaging_format = 2

id = "jitsi"
name = "Jitsi Meet"
description.en = "Video conferencing web application"
description.fr = "Application web de conférence vidéo"

version = "2.0.8922~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "Apache-2.0"
website = "https://jitsi.org/"
demo = "https://meet.jit.si/"
userdoc = "https://jitsi.org/user-faq/"
code = "https://github.com/jitsi/jitsi-meet"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

    [install.domain]
    type = "domain"

[resources]
    [resources.sources]
        [resources.sources.jitsi-meet-web]
        url = "https://download.jitsi.org/stable/jitsi-meet-web_1.0.7499-1_all.deb"
        sha256 = "b091603ecf638df299fb9ce8432fceac102e58b4621d7380907c4fc1d33735bd"
        format = "deb"
        rename = "jitsi-meet-web.deb"

        [resources.sources.jitsi-sctp]
        url = "https://github.com/jitsi/jitsi-sctp/archive/45bf9f296167f79a52cdc1b0e93bbfa4dc8c4976.tar.gz"
        sha256 = "1eead17b10d059bafe8e1b06a8351936b608e7514b131588deac61d24b859397"

        [resources.sources.jitsi-jicofo]
        url = "https://download.jitsi.org/stable/jicofo_1.0-1048-1_all.deb"
        sha256 = "76a8e63866541ac7689b0619aac8859022d0e5514d3fa7330ecbaffcc45226c3"
        format = "deb"
        rename = "jitsi-jicofo.deb"

        [resources.sources.jitsi-videobridge]
        url = "https://download.jitsi.org/stable/jitsi-videobridge2_2.3-41-ga8d8a786-1_all.deb"
        sha256 = "cd0fe7401830acbb2f31ba00687b8a91174b9a4aa3ac84f66427c6009c415450"
        format = "deb"
        rename = "jitsi-videobridge.deb"

        [resources.sources.usrsctp]
        url = "https://github.com/sctplab/usrsctp/archive/8e12cd9e01fc94d2e84ea1afa351c845966e116e.tar.gz"
        sha256 = "0574a31fecca543cf8e46c1bff441a3048ccf7d403da0543639db334e9a09b2f"

        [resources.sources.jitsi-meet-prosody]
        url = "https://download.jitsi.org/stable/jitsi-meet-prosody_1.0.7499-1_all.deb"
        sha256 = "afa88c1a02362709aef00ea85aa4694bb49512156ca946118ba397af1274b833"
        format = "deb"
        rename = "jitsi-meet-prosody.deb"

        [resources.sources.mod_auth_ldap]
        url = "https://hg.prosody.im/prosody-modules/raw-file/tip/mod_auth_ldap/mod_auth_ldap.lua"
        sha256 = "49c67ec86ec75ac8de93803be2ac7f907d1e9d3d22cd4c88fd48aaeed7a411e3"
        format = "lua"
        rename = "mod_auth_ldap.lua"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    
        [[resources.apt.extras]]
        repo = "deb http://security.debian.org/debian-security stretch/updates main"
        key = "https://ftp-master.debian.org/keys/archive-key-9-security.asc"
        packages = "#FIXME#$pkg_extra_depedencies_arm"
